import localFont from "next/font/local";
// import "swiper/swiper-bundle.min.css"; // Global Swiper styles
import "./globals.css";
// pages/_app.js
// import '../styles/globals.css'; // Your global styles

import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Footer from "@/components/Footer";
import { Spotlight } from "@/components/ui/Spotlight";
import { cn } from "@/lib/utils";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "lounge Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary cursor-default text-white w-full h-full`}
      >
        <Navbar />

        {children}

        <Footer />
      </body>
    </html>
  );
}
